project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about_websites.qmd

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true

editor: visual

publish:
  - gh-pages
