project:
  type: website
  output-dir: docs

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
      - href: pages/visualizations.qmd
      - href: pages/website_info.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual
