project:
  type: website
  output-dir: docs

website:
  title: "Heidi Lantz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - about_websites.qmd

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true

editor: visual
