project:
  type: website 

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: My Projects

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

# editor: visual

# overwrite any render-on-save option
editor:
  render-on-save: true
