project:
  type: website
  output-dir: docs

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.html
        text: Home
      - pages/projects.html
      - pages/visualizations.html
      - pages/website_info.html

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

# editor: visual

# overwrite any render-on-save option
editor:
  render-on-save: true
