project:
  type: website
  output-dir: docs

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: pages/projects.html
      - href: pages/visualizations.html
      - href: pages/website_info.html

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual
