project:
  type: website
  output-dir: docs

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - pages/projects.qmd
      - pages/visualizations.qmd
      - pages/website_info.qmd

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true

editor: visual
