---
title: "Heidi Lantz"
title-block-banner: true
toc: true
---

## About Me

Hi! I am a 5th year Statistics student at UBC. 

I am in a Bachelor of Science, majoring in statistics with a minor in data science.

My interests involve data science consulting, data visualization, actuarial science, and data engineering. Please take a look through my website to get a sense of who I am and what I like to do!

## Contact

Feel free to reach out to if you have any questions!

Here is my contact information:

-   **GitHub**: <https://github.com/hlan22>
-   **LinkedIn**: <https://www.linkedin.com/in/heidilantz/>
-   **Email**: [heidilantz22\@gmail.com](mailto:heidilantz22@gmail.com){.email}

## Guide to Other Pages

- [Home](#home)
  - Introduction to me, my general interests, and current events going on in my life.
- [My Projects](#my-projects)
  - Talks about my current and previous projects that I am proud of.
- [My Visualizations](#my-visualizations)
  - Showcases some visualizations I have made in the past that I am proud of.
- [All About Websites](#all-about-websites!)
  - Contains all the useful information I had learned about making websites while creating this one!
  
## Current Events

#### April 11th

Come see my STAT 450 capstone project poster board presentation!

#### March 8-9th, 2025

**CMD-F 2025 Hackathon Finalist: 3rd Place**

* Winner of “Social” category, and then received third place out of all the categories combined
* Winners received $200 and their project displayed on the cmd-f website (not uploaded yet).


