---
title: "My Projects"
toc: true
format:
  html:
    css: styles.css
---

This page will contain info about all my projects that I have done!

Outline:

* [Statistics Capstone Project](#capstone)
* [The Daily Grind (CMD-F Hackathon)](#cmdf)
* [Easy EDA (Personal Project)](#easy)
* [DSCI 310](#reproducible)
* [Weather Extremes Research](#research)
* [ASA Datafest](#datafest)


## Statistics Capstone Project {#capstone}

* With guidance from Dr. Rodolfo Lourenzutti, I worked for a client analyzing changes in glaucoma eye surgery in an apprentice type of job.
* Real client work, regular meetings with the professor presenting work, poster board and oral presentations
* Produced reports, coding, and worked directly for the client using the R coding language and GitHub
* Learned about complications with study design, model selection, and effective communication
* See poster board session listing: <https://www.stat.ubc.ca/poster-session-stat-450-2>

---

## The Daily Grind (CMD-F Hackathon) {#cmdf}

* March 8-9th, 2025, 24 hour hackathon
* **Winner of “Social Track”** in a 24 hour hackathon, Won **3rd place overall**, with 50+ projects and 200+ participants
* Presented work to 7 judges individually, and in the final round presented in front of the entire hackathon community.
* See the project at: <https://devpost.com/software/the-daily-grind>

---

## Easy EDA (Personal Project) {#easy}

* Personal project such that you can “automate” EDA for any given dataset. 
* I hope to make an R package such that functions will quickly and easily create proper plots based on data types, for any and all columns. All code will be done with R initially, but will expand to Python too, for interactive visuals.
* [Link to the Repo](https://github.com/hlan22/easy_eda)


---

## DSCI 310 Group Project {#reproducible}

* Create a statistical analysis that incorporates these main ideas:
  * Data Pipelines
  * Make and Makefiles
  * Dockerfiles
  * Creating an R Package
* See the repository here: <https://github.com/DSCI-310-2025/dsci-310-group-7-data-dudes>

---

## Weather Extremes Research {#research}

* Working at UBC from May to August 2024 under an URSA NSERC scholarship
* Working under professors Harry Joe and Natalia Nolde, I found patterns and explanations for climate extremes. 
* Dealt with Canadian weather data, relating to floods, droughts, and wildfires using Python and R languages. 
* Completed EDA and used various statistical analyses to gain insight into weather patterns and time series analysis. 
* Analyzed many research papers, presented work weekly, and assisted both professors with various tasks.
* Will be publishing work on a public repository soon!

---

## ASA DataFest {#datafest}

* A 48 hour hackathon in a team of 3
* Created a fully reproducible project, with a clear statistical analysis
* Created a dashboard, demonstration video, presentation using quarto, and analysis using a bayesian model
* Project topic and workcan only be revealed after May 3, 2025
* Info about ASA DataFest: <https://ww2.amstat.org/education/datafest/>


:::: purplebox
::: center
**NOTICE!**\
Please know that I am still updating this website... It will be finished soon :)
:::
::::
