project:
  type: website
  output-dir: ../docs 

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

# editor: visual

# overwrite any render-on-save option
editor:
  render-on-save: true
