---
title: "Heidi Lantz"
title-block-banner: true
toc: true
format:
  html:
    css: styles.css
---

## About Me

Hello! 

I am a BSc. student at UBC, graduating in May!

I am majoring in statistics and have a minor in data science.

My interests involve consulting, data visualization, actuarial science, and data engineering. Please feel free to take a look through my website to get a sense of who I am and what I like to do!

## Contact

Feel free to reach out to if you have any questions!

Here is my contact information:

-   **GitHub**: <https://github.com/hlan22>
-   **LinkedIn**: <https://www.linkedin.com/in/heidilantz/>
-   **Email**: [heidilantz22\@gmail.com](mailto:heidilantz22@gmail.com){.email}

## Guide to Other Pages

-   [Home](index.html)
    -   Introduction to me, my general interests, and current events going on related to my career in my life.
-   [My Projects](projects.html)
    -   Talks about my current and previous projects that I am proud of.
-   [My Visualizations](visualizations.html)
    -   Showcases some visualizations I have made in the past that I am proud of.
-   [Courses and Certifications](courses.html)
    -   Talks about all the courses I have taken and the information I have earned from them! 
-   [All About Websites](website_info.html)
    -   Contains all the useful information I had learned about making websites while creating this one!

## Current Events

::: bluebox
#### April 11th, 2025

Come see my STAT 450 capstone project poster board presentation!
:::

::: bluebox
#### March 21-23rd, 2025

I participated in the ASA DataFest, a 48 hour data science hackathon!
:::

::: bluebox
#### March 8-9th, 2025

**CMD-F 2025 Hackathon Finalist: 3rd Place**

-   Winner of “Social” category, and then received third place out of all the categories combined
-   Winners received \$200 and their project displayed on the cmd-f website (not uploaded yet).
:::

:::: purplebox
::: center
**NOTICE!**\
Please know that I am still updating this website... I hope to finish it soon :)
:::
::::
