project:
  type: website
  output-dir: docs # put rendered info into docs folder

website:
  title: "Heidi's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - visualizations.qmd
      - website_info.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

# editor: visual

# overwrite any render-on-save option
editor:
  render-on-save: true
