name: Build and Render Website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: |
          cd website
          quarto render

      - name: Upload site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website/_site 
