name: Build and Render Website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("quarto", "tidyverse", "rmarkdown"))'

      - name: Render site
        run: |
          quarto render

      - name: Upload site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs 
